import Hero from '@/components/Hero'
import type { NextPage } from 'next'
import Head from 'next/head'
import MyHeader from '../components/MyHeader'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <MyHeader />
        <Hero />
      </main>
    </>
  )
}

export default Home
